# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7be61d25e4e3d4ac574a77abd84370df130e11f02a6cb93fa0079b6ac0b6e137aef07996e7de91d995420c6d095b39a0ae6b5857e4a0a4ce345ab4a64df80be

test:
  secret_key_base: 9dfc90a57406491fc0dba5ba24a25b2f9f7ccb87da683b1ce0a91a71f465c5510546dd21d3b5877f322a1ae4825e5d7fc262dd2ebe8561655f1fcc92fc31454c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
